# Mettiamo tutto sotto una chiave principale 'tesina'
tesina:
  titolo: "INCONTRI"
  sottotitolo: "Acousmatic concert documentation by  z⁻¹"
  autore: "z⁻¹" # Usiamo 'autore' invece di 'candidato.nome' per coerenza con Pandoc
  
  # Dati per il conservatorio
  conservatorio: "Conservatorio di Atlantide"
  citta: "Atlantide"
  corso: "Musica Elettronica"

  # Dati specifici dell'esame
  esame: "COME01"
  data: "10/07/2025"

  
environment:
  font: #arial
